// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package dyn

#DynRecordResource: {
	type:  string
	value: string
	zone:  string
	name?: string
}
#Resources: dyn_record?: [_]: #DynRecordResource
