// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package scaleway

#Provider: scaleway: {
	access_key?:      string
	organization?:    string
	organization_id?: string
	region?:          string
	secret_key?:      string
	token?:           string
	zone?:            string
}
