// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package local

#LocalFileDataSource: filename: string
#DataSources: local_file?: [_]: #LocalFileDataSource
