// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package infoblox

#InfobloxNetworkDataSource: {
	cidr:               string
	tenant_id:          string
	gateway?:           string
	id?:                string
	network_name?:      string
	network_view_name?: string
}
#DataSources: infoblox_network?: [_]: #InfobloxNetworkDataSource
