// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package exoscale

#Provider: exoscale: {
	compute_endpoint?: string
	config?:           string
	delay?:            number
	dns_endpoint?:     string
	gzip_user_data?:   bool
	key?:              string
	profile?:          string
	region?:           string
	secret?:           string
	timeout?:          number
	token?:            string
}
