// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package archive

#ArchiveFileResource: {
	output_path: string
	type:        string
	excludes?: [string, ...]
	source_content?:          string
	source_content_filename?: string
	source_dir?:              string
	source_file?:             string
	source?: [{
		content:  string
		filename: string
	}, ...]
}
#Resources: archive_file?: [_]: #ArchiveFileResource
