// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package pureport

#Provider: pureport: {
	api_key?:      string
	api_secret?:   string
	api_url?:      string
	auth_profile?: string
}
