// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package signalfx

#Provider: signalfx: {
	api_url?:         string
	auth_token?:      string
	custom_app_url?:  string
	timeout_seconds?: number
}
