// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package dnsimple

#DnsimpleRecordResource: {
	domain: string
	name:   string
	type:   string
	value:  string
	ttl?:   string
}
#Resources: dnsimple_record?: [_]: #DnsimpleRecordResource
