// Generated by cue-terraform-gen (https://github.com/tnarg/cue_terraform_gen). DO NOT EDIT.
package vmc

#Provider: vmc: {
	org_id:        string
	refresh_token: string
	csp_url?:      string
	vmc_url?:      string
}
